### ISSUE TITLE
Serd parses prefixed IRIs that contain illegal Unicode characters

### ISSUE THREAD

**Issue by wouterbeek** [drobilla/serd#5]
Serd parses prefixed IRIs that contain illegal Unicode characters in their local name.

For example, the following Turtle snippet appears in an actual data file (notice that the underscores are the illegal Unicode character `EN DASH (U+2013)`:

```ttl
@prefix dbp: <http://dbpedia.org/property/> .
@prefix dbr: <http://dbpedia.org/resource/> .
dbr:Germany_at_the_2006–08_European_Nations_Cup dbp:stadium     dbr:Amsterdam .
```
Serdi parses this snippet, but it should raise an error:

```bash
serdi unicode.ttl
<http://dbpedia.org/resource/Germany_at_the_2006\u201308_European_Nations_Cup> <http://dbpedia.org/property/stadium> <http://dbpedia.org/resource/Amsterdam> .
```

Tested with Serd 0.28.0.

**Comment by drd-ableton** [comment]
The underscores are just ASCII, it's the dash between the years.

I didn't implement that stuff originally because it's kind of annoying and slower to have to parse UTF-8 just to get the code to check against a big list in a syntax that otherwise doesn't require this (if you're producing UTF-8 output anyway).

The existing escaping behaviour of reading more or less whatever in prefixed names and URIs seems useful though, serd is outputting valid Turtle here.  I suppose it can just fail and bail out on parsing in strict mode and do what it currently does in lax mode.

**Comment by wouterbeek** [comment]
+1 for a distinction between strict and lax mode.

BTW I do not see the rational behind not allowing the Unicode dash in this position.  What could be the rational behind this in the standard?

**Comment by drd-ableton** [comment]
Me neither, no idea.  The general clunkiness and mixing of concerns in the grammar (especially since RDF 1.1) is a big flaw, IMO, but so it goes.

The official test suite doesn't hit any of this stuff either.

**Comment by drobilla** [comment]
Fixed in https://github.com/drobilla/serd/commit/1cd321825c52eddd4175cb4ec58ae8d7ad2da48d
